name: code_bolanon
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  carousel_slider: ^5.0.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_layout_grid: ^2.0.7
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  lottie: ^3.3.1
  number_editing_controller: ^1.3.1
  percent_indicator: ^4.2.4
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  supabase_flutter: ^2.8.3
  curved_navigation_bar: ^1.0.6
  google_fonts: ^6.2.1
  intl: ^0.19.0
  animate_do: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  # image_path: "assets/icon/icon.png"
  image_path: "assets/icon/icons.png"
  min_sdk_android: 23 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/trainer_animation.json
    - assets/lottie/trainee_animation.json
    - assets/animations/
    - assets/animations/team_sucesss.json
    - assets/animations/user_friendly.json
    - assets/animations/task_creations.json
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
