import 'package:code_bolanon/services/api_service.dart';
import 'package:code_bolanon/services/auth_service.dart';
import 'package:code_bolanon/services/course_service.dart';
import 'package:code_bolanon/services/file_service.dart';
import 'package:code_bolanon/services/image_service.dart';
import 'package:code_bolanon/services/lesson_service.dart';
import 'package:code_bolanon/services/tag_service.dart';
import 'package:code_bolanon/services/theme_service.dart';
import 'package:code_bolanon/services/transactions_service.dart';
import 'package:code_bolanon/services/user_service.dart';
import 'package:code_bolanon/ui/bottom_sheets/notice/notice_sheet.dart';
import 'package:code_bolanon/ui/dialogs/basic/basic_dialog.dart';
import 'package:code_bolanon/ui/dialogs/error/error_dialog.dart';
import 'package:code_bolanon/ui/dialogs/info_alert/info_alert_dialog.dart';
import 'package:code_bolanon/ui/dialogs/receipt/receipt_dialog.dart';
import 'package:code_bolanon/ui/dialogs/success/success_dialog.dart';
import 'package:code_bolanon/ui/dialogs/warning/warning_dialog.dart';
import 'package:code_bolanon/ui/views/add_lesson/add_lesson_view.dart';
import 'package:code_bolanon/ui/views/auth/auth_view.dart';
import 'package:code_bolanon/ui/views/available_courses/available_courses_view.dart';
import 'package:code_bolanon/ui/views/course_details/course_details_view.dart';
import 'package:code_bolanon/ui/views/home/home_view.dart';
import 'package:code_bolanon/ui/views/learner_courses/learner_courses_view.dart';
import 'package:code_bolanon/ui/views/learner_home/learner_home_view.dart';
import 'package:code_bolanon/ui/views/lesson_details/lesson_details_view.dart';
import 'package:code_bolanon/ui/views/lessons_full/lessons_full_view.dart';
import 'package:code_bolanon/ui/views/main_body/main_body_view.dart';
import 'package:code_bolanon/ui/views/menu/menu_view.dart';
import 'package:code_bolanon/ui/views/onboarding/onboarding_view.dart';
import 'package:code_bolanon/ui/views/profile/profile_view.dart';
import 'package:code_bolanon/ui/views/trainer_courses/trainer_courses_view.dart';
import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
import 'package:code_bolanon/ui/views/learner_wishlists/learner_wishlists_view.dart';
import 'package:code_bolanon/ui/views/payment/payment_view.dart';
import 'package:code_bolanon/services/payment_service.dart';
import 'package:code_bolanon/services/stripe_service.dart';
import 'package:code_bolanon/ui/views/forgot_password/forgot_password_view.dart';
import 'package:code_bolanon/services/forgot_password_service.dart';
import 'package:code_bolanon/ui/views/tos/tos_view.dart';
import 'package:code_bolanon/services/tech_stack_service.dart';
import 'package:code_bolanon/ui/views/trainer_analytics/trainer_analytics_view.dart';
import 'package:code_bolanon/services/analytics_service.dart';
import 'package:code_bolanon/ui/dialogs/metric_selection/metric_selection_dialog.dart';

import 'package:code_bolanon/services/wishlist_service.dart';
import 'package:code_bolanon/services/registration_service.dart';
import 'package:code_bolanon/ui/views/change_password/change_password_view.dart';
import 'package:code_bolanon/ui/views/edit_profile/edit_profile_view.dart';
import 'package:code_bolanon/ui/views/trainer_appointment_home/trainer_appointment_home_view.dart';
import 'package:code_bolanon/ui/views/trainer_schedules/trainer_schedules_view.dart';
import 'package:code_bolanon/ui/views/learner_appointment_home/learner_appointment_home_view.dart';
import 'package:code_bolanon/ui/views/learner_schedule/learner_schedule_view.dart';
import 'package:code_bolanon/services/appointment_service.dart';
import 'package:code_bolanon/services/selected_stack_service.dart';
import 'package:code_bolanon/ui/views/manage_stack/manage_stack_view.dart';
import 'package:code_bolanon/services/dialog_helper_service.dart';

@StackedApp(
  routes: [
    MaterialRoute(page: HomeView),
    MaterialRoute(page: OnboardingView),
    MaterialRoute(page: AuthView),
    MaterialRoute(page: MainBodyView),
    MaterialRoute(page: ProfileView),
    MaterialRoute(page: MenuView),
    MaterialRoute(page: LearnerHomeView),
    MaterialRoute(page: TrainerCoursesView),
    MaterialRoute(page: CourseDetailsView),
    MaterialRoute(page: AddLessonView),
    MaterialRoute(page: AvailableCoursesView),
    MaterialRoute(page: LessonDetailsView),
    MaterialRoute(page: LessonsFullView),
    MaterialRoute(page: LearnerCoursesView),
    MaterialRoute(page: LearnerWishlistsView),
    MaterialRoute(page: PaymentView),
    MaterialRoute(page: ForgotPasswordView),
    MaterialRoute(page: TosView),
    MaterialRoute(page: TrainerAnalyticsView),
    MaterialRoute(page: ChangePasswordView),
    MaterialRoute(page: EditProfileView),
    MaterialRoute(page: TrainerAppointmentHomeView),
    MaterialRoute(page: TrainerSchedulesView),
    MaterialRoute(page: LearnerAppointmentHomeView),
    MaterialRoute(page: LearnerScheduleView),
    MaterialRoute(page: ManageStackView),
// @stacked-route
  ],
  dependencies: [
    LazySingleton(classType: BottomSheetService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: AuthService),
    LazySingleton(classType: ThemeService),
    LazySingleton(classType: SnackbarService),
    LazySingleton(classType: ApiService),
    LazySingleton(classType: CourseService),
    LazySingleton(classType: ImageService),
    LazySingleton(classType: UserService),
    LazySingleton(classType: LessonsService),
    LazySingleton(classType: FileService),
    LazySingleton(classType: TagService),
    LazySingleton(classType: PaymentService),
    LazySingleton(classType: StripeService),
    LazySingleton(classType: ForgotPasswordService),
    LazySingleton(classType: TechStackService),
    LazySingleton(classType: AnalyticsService),

    LazySingleton(classType: WishlistService),
    LazySingleton(classType: RegistrationService),
    LazySingleton(classType: DialogHelperService),
    LazySingleton(classType: AppointmentService),
    LazySingleton(classType: SelectedStackService),
    LazySingleton(classType: TransactionsService),
// @stacked-service
  ],
  bottomsheets: [
    StackedBottomsheet(classType: NoticeSheet),
    // @stacked-bottom-sheet
  ],
  dialogs: [
    StackedDialog(classType: InfoAlertDialog),
    StackedDialog(classType: BasicDialog),
    StackedDialog(classType: SuccessDialog),
    StackedDialog(classType: ErrorDialog),
    StackedDialog(classType: WarningDialog),
    StackedDialog(classType: MetricSelectionDialog),
    StackedDialog(classType: ReceiptDialog),
    // @stacked-dialog
  ],
)
class App {}
